#!/bin/bash
### BEGIN INIT INFO
# Provides:          zivame
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Example init script
# Description:       Start/stop an example script
### END INIT INFO

DESC="test script"
NAME=newstack
App_path='/opt/zivame/app'
#DAEMON=

CMD="$1"
NodeVersion="$2"
LogPath="$2"

# DEV mode requires V2 docker-compose as it uses `docker-compose run` and needs
# a different order to containers start (i.e. nginx needs to be started before
# hubot even though the actual dependency is the other direction). V2 creates
# a special network where all the containers see each other we we leverage that
# in DEV.
validate_compose_1_6_plus() {
    local docker_compose_verson="$(docker-compose --version | cut -d' ' -f3)"
    if [[ !  "${docker_compose_verson}" =~ ^[1-9]\.[6-9] && ! "${docker_compose_verson}" =~ ^[1-9]\.1[0-9] ]]; then
        echo "This command requires docker-compose 1.6.0+"
        exit 1
    fi
}
validate_compose_1_6_plus

case "${CMD}" in
    start)
        start_status=$(logpath="${LogPath}" docker-compose -f $App_path/docker-compose.yml up -d)
        echo "start_status"
        status=$(docker-compose -f $App_path/docker-compose.yml ps)
        echo "$status" 
        echo "Staring ...."
        ;;
    restart)
        restop_status=$(logpath="${LogPath}" docker-compose -f $App_path/docker-compose.yml down)
        echo "start_status"
        restart_status=$(logpath="${LogPath}" docker-compose -f $App_path/docker-compose.yml up -d)
        echo "$status" 
        echo "Staring ...."
        ;;
    scale)
       count_before=$(logpath="${LogPath}" sudo docker-compose -f $App_path/docker-compose.yml ps |wc -l)
        echo "$(($count_before - $2))" 
        if [[ "$2" -gt 1 || "$(($count_before - $2 - 3))" -ne "0" ]]; then
        for (( i=1; i <= $2; ++i )); do
        logpath=$3_$i docker-compose -f $App_path/docker-compose.yml scale zivame=$i ;
        done
        else
        echo "Already Scaled to 1 so skipped!!!"
        fi
        echo "$scale_status"       
        ;;
    stop)
        docker-compose -f $App_path/docker-compose.yml down 
        ;;
    rebuild)
        nversion="${NodeVersion}" docker-compose -f $App_path/docker-compose.yml build 
        ;;
    state)
        status=$(docker-compose -f $App_path/docker-compose.yml ps)
        echo "$status" 
        ;; 
    health)
        ports=$(sudo docker-compose -f $App_path/docker-compose.yml ps |grep -o -P '(?<=:).*(?=-)');
        for port in $ports; do while(true); do if(curl -I localhost:$port|head -n1|grep 200) ;then break;else sleep 5;fi; done  done
        ;;  
    config-reload)
        ports=$(sudo docker-compose -f $App_path/docker-compose.yml ps |awk '{print $6}' | grep 0.0.0.0 | grep -o -P '(?<=:).*(?=-)') ;upstream="";for i in $ports; do upstream+="server localhost:$i;"; done ; ngxupstream="upstream app_upstream { $upstream }";echo "$ngxupstream";sudo sed -i -E "s/(upstream app_upstream)+.\{(.*?)\}/$ngxupstream/" /etc/nginx/sites-enabled/default && sudo  nginx -t && sudo service nginx reload
        ;;     
    logs)
        log_status=$(docker-compose -f $App_path/docker-compose.yml logs)
        echo "$log_status" 
        ;;
    clean)
        clean_status=$(sudo docker rmi -f $(sudo docker images | grep "<none>" | awk "{print \$3}"))
        echo "$clean_status" 
        ;;
    *)
        echo
        echo "Usage: $0 start|stop|rebuild|logs|health|config-reload dev"
        echo
        exit 1
esac

exit 0
